Fix the helper text with the right option name
soluble-ai/soluble-cli pull request #562
Opened 2022-12-09 09:15 UTC by hemanthgk10

Signed-off-by: Hemanth Gokavarapu <hemanth@soluble.ai>

## JIRA ISSUE
https://lacework.atlassian.net/browse/RAIN-44805

## DESCRIPTION
The helper text is saying different option at different level which is confusing. See the screenshot below

2022-12-12 14:59 UTC, declanwilson-lw approved these changes
lgtm

2022-12-12 16:47 UTC, slshen requested changes

2022-12-12 16:47 UTC, slshen commented on cmd/configure/configure.go
> +			log.Errorf("You are a member of multiple IAC organizations.  A specific one must be specified with ----iac-organization.")
too many dashes

2022-12-13 04:18 UTC, hemanthgk10 commented on cmd/configure/configure.go
> +			log.Errorf("You are a member of multiple IAC organizations.  A specific one must be specified with ----iac-organization.")
good catch fixed it.

2022-12-13 05:26 UTC, merged